#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Allied Telesis
  description: Sets up trustpoint for OpenFlow with SSL
  company: Allied Telesis
  license: GPLv3
  min_ansible_version: 2.19
  galaxy_tags: []
dependencies: []
