#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Allied Telesis
  description: Configures Openflow
  company: Allied Telesis
  license: GPLv3
  min_ansible_version: 2.19
  galaxy_tags: []
dependencies: []
