---
- hosts: all
  connection: network_cli
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: Merge provided configuration with device configuration
      awplus_lacp:
        config:
          system:
            priority: 123
            global_passive_mode: True
        state: merged

    - name: Delete global lacp attribute
      awplus_lacp:
        config:
          system:
            priority: 123
            global_passive_mode: True
        state: deleted
