---
- hosts: all
  connection: network_cli
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: Override merge
      awplus_l3_interfaces:
        config:
          - name: vlan2
            vrf: VRF1
        state: merged
