---
- name: Get LLDP neighbour information
  connection: network_cli
  hosts: all
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: Run show lldp neighbours on remote devices
      alliedtelesis.awplus.awplus_command:
        commands: show lldp neighbors detail
